language: python
cache:
  directories:
      - $HOME/.cache/pip
      - $HOME/.cache/pre-commit
stages:
- name: linting
- name: test
- name: deploy
  if: tag IS present
python:
- 2.7
- 3.5
- 3.6
install:
- pip install tox-travis
- pip install codecov
script:
- tox
after_success:
- codecov
jobs:
  include:
  - stage: linting
    python: 3.6
    env: TOXENV=pre-commit
  - stage: linting
    env: TOXENV=check-readme
